### ISSUE TITLE
Work around for generating code coverage for the updated rooibos

### ISSUE THREAD

**Issue by nidhi2303** [rokucommunity/meetup#14]
I tried the work around mentioned in the readme of rooibos for roku: https://github.com/georgejecook/rooibos/blob/master/docs/index.md#generate-code-coverage there is a  line that says that there is command line which can be used to generate code coverage for the package but it does not include the command line statement. Can someone help me to get the coverage with current roobios version.

**Comment by georgejecook** [comment]
Hi, please raise this issue in the rooibos issues: https://github.com/georgejecook/rooibos/issues
